name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        builder: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build project
        run: make

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.builder }}
          path: ./build
